### ISSUE TITLE
Bug restarting nodebb

### ISSUE THREAD

**Issue by exomarty** [yariplus/nodebb-plugin-featured-topics-extended#11]
If you select show all topics on the widget and set max topics limit i get this
last version and nodebb 1.4.0, was happening on 1.3.x too

 - error: MongoError: limit requires an integer
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/no                                                                                                         de_modules/mongodb-core/lib/error.js:31:11)
    at Cursor.limit (/var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:60                                                                                                         5:49)
    at getSortedSetRangeByScore (/var/foroexodo/nodebb/src/database/mongo/sorted                                                                                                         .js:211:5)
    at module.getSortedSetRevRangeByScore (/var/foroexodo/nodebb/src/database/mo                                                                                                         ngo/sorted.js:176:3)
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:760:23
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:166:37
    at fn (/var/foroexodo/nodebb/node_modules/async/lib/async.js:746:34)
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:1213:16
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:166:37
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:706:43
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/var/foroexodo/nodebb/node_modules/async/lib/asyn                                                                                                         c.js:710:44)
    at getFeaturedTopics (/var/foroexodo/nodebb/node_modules/nodebb-plugin-featu                                                                                                         red-topics-extended/lib/plugin.js:476:19)
    at /var/foroexodo/nodebb/node_modules/nodebb-plugin-featured-topics-extended                                                                                                         /lib/plugin.js:497:5
    at /var/foroexodo/nodebb/src/database/mongo/hash.js:69:4
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:9                                                                                                         6:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/collection.js:1403:5
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:9                                                                                                         6:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:675:5
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/m                                                                                                         ongodb-core/lib/cursor.js:172:5)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mon                                                                                                         godb-core/lib/cursor.js:682:5)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/                                                                                                         cursor.js:593:7
    at queryCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mo                                                                                                         ngodb-core/lib/cursor.js:254:5)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/                                                                                                         connection/pool.js:436:18
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)
MongoError: limit requires an integer
    at Function.MongoError.create (/var/foroexodo/nodebb/node_modules/mongodb/no                                                                                                         de_modules/mongodb-core/lib/error.js:31:11)
    at Cursor.limit (/var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:60                                                                                                         5:49)
    at getSortedSetRangeByScore (/var/foroexodo/nodebb/src/database/mongo/sorted                                                                                                         .js:211:5)
    at module.getSortedSetRevRangeByScore (/var/foroexodo/nodebb/src/database/mo                                                                                                         ngo/sorted.js:176:3)
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:760:23
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:166:37
    at fn (/var/foroexodo/nodebb/node_modules/async/lib/async.js:746:34)
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:1213:16
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:166:37
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:706:43
    at /var/foroexodo/nodebb/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/var/foroexodo/nodebb/node_modules/async/lib/asyn                                                                                                         c.js:710:44)
    at getFeaturedTopics (/var/foroexodo/nodebb/node_modules/nodebb-plugin-featu                                                                                                         red-topics-extended/lib/plugin.js:476:19)
    at /var/foroexodo/nodebb/node_modules/nodebb-plugin-featured-topics-extended                                                                                                         /lib/plugin.js:497:5
    at /var/foroexodo/nodebb/src/database/mongo/hash.js:69:4
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:9                                                                                                         6:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/collection.js:1403:5
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/lib/utils.js:9                                                                                                         6:12)
    at /var/foroexodo/nodebb/node_modules/mongodb/lib/cursor.js:675:5
    at handleCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/m                                                                                                         ongodb-core/lib/cursor.js:172:5)
    at nextFunction (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mon                                                                                                         godb-core/lib/cursor.js:682:5)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/                                                                                                         cursor.js:593:7
    at queryCallback (/var/foroexodo/nodebb/node_modules/mongodb/node_modules/mo                                                                                                         ngodb-core/lib/cursor.js:254:5)
    at /var/foroexodo/nodebb/node_modules/mongodb/node_modules/mongodb-core/lib/                                                                                                         connection/pool.js:436:18
    at nextTickCallbackWith0Args (node.js:436:9)
    at process._tickCallback (node.js:365:13)

**Comment by yariplus** [comment]
Yikes, this should really be fixed in core. Since redis accepts strings, the dbal should call parseInt for mongo.

**Comment by yariplus** [comment]
I will send them a PR.

**Comment by exomarty** [comment]
i just write an integer anyways

**Comment by yariplus** [comment]
I updated the plugin, should work now.

**Comment by exomarty** [comment]
works ok now , only issue i have seen is savng widgets on another template makes the list to appear empty , i have to back to the fatured widget and save it again
closing this
