### ISSUE TITLE
Build issue on nodebb 1.19.5

### ISSUE THREAD

**Issue by vgmoose** [yariplus/nodebb-plugin-featured-topics-extended#52]
Thanks for this plugin! I'm seeing the following build issue on 1.19.5 nodebb, after installing and enabling (0.10.0):
```
2022-04-07T20:26:52.351Z [4567/17209] - error: [build]          requirejs modules  build failed
2022-04-07T20:26:52.352Z [4567/17209] - error: [build] Encountered error during build step
Error: Error minifying undefined
TypeError: Cannot read properties of null (reading 'figure_out_scope')
    at Object.minify (eval at <anonymous> (/usr/src/app/node_modules/uglify-es/tools/node.js:1:1), <anonymous>:14864:38)
    at minifyAndSave (/usr/src/app/src/meta/minifier.js:193:26)
    at /usr/src/app/src/meta/minifier.js:161:9
    at minifyAndSave (/usr/src/app/src/meta/minifier.js:203:9)
    at /usr/src/app/src/meta/minifier.js:161:9
2022-04-07T20:26:52.352Z [4567/17209] - error: admin.reload
Error: Error minifying undefined
TypeError: Cannot read properties of null (reading 'figure_out_scope')
    at Object.minify (eval at <anonymous> (/usr/src/app/node_modules/uglify-es/tools/node.js:1:1), <anonymous>:14864:38)
    at minifyAndSave (/usr/src/app/src/meta/minifier.js:193:26)
    at /usr/src/app/src/meta/minifier.js:161:9
    at minifyAndSave (/usr/src/app/src/meta/minifier.js:203:9)
    at /usr/src/app/src/meta/minifier.js:161:9
2022-04-07T20:31:24.219Z [4567/17209] - error: plugins.boardStats.get
Error: [[error:revalidate-failure]]
    at validateSession (/usr/src/app/src/socket.io/index.js:209:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async onMessage (/usr/src/app/src/socket.io/index.js:153:3)
```

Is this related to v2 changes? v0.6.0 is able to install and builds when added manually

**Comment by yariplus** [comment]
Can you try 0.10.1?
